[[link]]
source = "nvim"
target = "~/.config/nvim"

[[link]]
source = "yazi"
target = "~/.config/yazi"

[[link]]
source = "kitty"
target = "~/.config/kitty"
requires = ["+has_kitty"]

[[link]]
source = "tmux"
target = "~/.config/tmux"
requires = ["+has_tmux"]

[[link]]
source = "taplo/taplo.toml"
target = "~/.config/taplo/taplo.toml"
requires = ["+has_taplo"]

[[install]]
name = "tmux-tpm"
check = "stat ~/.config/tmux/plugins/tpm"
requires = ["+has_tmux"]
install = """#!/bin/bash
    mkdir -p ~/.config/tmux/plugins
    git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
"""


[detectors]
has_tmux = { enable_if = "command -v tmux" }
has_taplo = { enable_if = "command -v taplo" }
has_kitty = { enable_if = "command -v kitty" }
